tasks: 
    - baseline

baseline:
   batch_size: 32
   pretrained_model: bert-base-uncased
   seed: 42
   max_epochs: 5
   tasks:
      - cola
      - sst2
      - mnli
      - mrpc
      - qqp
      - stsb
      - qnli
      - rte
   cola:
      outfile: CoLA.tsv
      metric_name: matthews_correlation
   sst2:
      outfile: SST-2.tsv
      metric_name: accuracy
   mrpc:
      outfile: MRPC.tsv
      metric_name: accuracy
   qqp:
      outfile: QQP.tsv
      metric_name: accuracy
   stsb:
      outfile: STS-B.tsv
      metric_name: pearson
   mnli:
      outfile: ['MNLI-m.tsv', 'MNLI-mm.tsv']
      metric_name: accuracy_matched
   qnli:
      outfile: QNLI.tsv
      metric_name: accuracy
   rte:
      outfile: RTE.tsv
      metric_name: accuracy
