tasks: 
    - baseline

baseline:
   batch_size: 32
   pretrained_model: bert-base-uncased
   seed: 42
   max_epochs: 5
   tasks:
      - mnli
      - cola
      - sst2
      - mrpc
      - qqp
      - stsb
      - qnli
      - rte
   cola:
      output_prefix: CoLA
      metric_name: matthews_correlation
   sst2:
      output_prefix: SST-2
      metric_name: accuracy
   mrpc:
      output_prefix: MRPC
      metric_name: accuracy
   qqp:
      output_prefix: QQP
      metric_name: accuracy
   stsb:
      output_prefix: STS-B
      metric_name: pearson
   mnli:
      output_prefix: MNLI
      metric_name: accuracy_matched
   qnli:
      output_prefix: QNLI
      metric_name: accuracy
   rte:
      output_prefix: RTE
      metric_name: accuracy
